# Generated by Django 3.0.6 on 2022-07-02 00:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=7)),
                ('city', models.CharField(blank=True, default='', max_length=25)),
                ('state', models.CharField(blank=True, default='', max_length=25)),
                ('temperatures', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
